<?php
    include('./connectDB.php');
    if(isset($_SESSION['user'])){
        unset($_SESSION['user']);
        unset($_SESSION['datagiohang']);
        unset($_SESSION['giohang']);
    }
    header('location:index.php')
 ?>